2022-11-03T03:41:28,745 Using pip 21.2.4 from C:\Users\lnico\anaconda3\lib\site-packages\pip (python 3.9)
2022-11-03T03:41:28,749 Non-user install because site-packages writeable
2022-11-03T03:41:28,762 Created temporary directory: C:\Users\lnico\AppData\Local\Temp\pip-ephem-wheel-cache-8x0et21h
2022-11-03T03:41:28,764 Created temporary directory: C:\Users\lnico\AppData\Local\Temp\pip-req-tracker-xq96ynsj
2022-11-03T03:41:28,764 Initialized build tracking at C:\Users\lnico\AppData\Local\Temp\pip-req-tracker-xq96ynsj
2022-11-03T03:41:28,764 Created build tracker: C:\Users\lnico\AppData\Local\Temp\pip-req-tracker-xq96ynsj
2022-11-03T03:41:28,765 Entered build tracker: C:\Users\lnico\AppData\Local\Temp\pip-req-tracker-xq96ynsj
2022-11-03T03:41:28,767 Created temporary directory: C:\Users\lnico\AppData\Local\Temp\pip-install-_yji_8n_
2022-11-03T03:41:28,784 Collecting git+https://github.com/ACCLAB/OSAR.git@master (from -r requirements.txt (line 1))
2022-11-03T03:41:28,785   Created temporary directory: C:\Users\lnico\AppData\Local\Temp\pip-req-build-2b2cbp7u
2022-11-03T03:41:28,786   Cloning https://github.com/ACCLAB/OSAR.git (to revision master) to c:\users\lnico\appdata\local\temp\pip-req-build-2b2cbp7u
2022-11-03T03:41:28,787   Running command git clone -q https://github.com/ACCLAB/OSAR.git 'C:\Users\lnico\AppData\Local\Temp\pip-req-build-2b2cbp7u'
2022-11-03T03:41:34,808   fatal: this operation must be run in a work tree
2022-11-03T03:41:34,808   warning: Clone succeeded, but checkout failed.
2022-11-03T03:41:34,809   You can inspect what was checked out with 'git status'
2022-11-03T03:41:34,809   and retry with 'git restore --source=HEAD :/'

2022-11-03T03:41:34,819 WARNING: Discarding git+https://github.com/ACCLAB/OSAR.git@master. Command errored out with exit status 128: git clone -q https://github.com/ACCLAB/OSAR.git 'C:\Users\lnico\AppData\Local\Temp\pip-req-build-2b2cbp7u' Check the logs for full command output.
2022-11-03T03:41:34,820 ERROR: Command errored out with exit status 128: git clone -q https://github.com/ACCLAB/OSAR.git 'C:\Users\lnico\AppData\Local\Temp\pip-req-build-2b2cbp7u' Check the logs for full command output.
2022-11-03T03:41:34,821 Exception information:
2022-11-03T03:41:34,821 Traceback (most recent call last):
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
2022-11-03T03:41:34,821     status = self.run(options, args)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
2022-11-03T03:41:34,821     return func(self, options, args)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
2022-11-03T03:41:34,821     requirement_set = resolver.resolve(
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 75, in resolve
2022-11-03T03:41:34,821     collected = self.factory.collect_root_requirements(root_reqs)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 471, in collect_root_requirements
2022-11-03T03:41:34,821     req = self._make_requirement_from_install_req(
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 448, in _make_requirement_from_install_req
2022-11-03T03:41:34,821     raise self._build_failures[ireq.link]
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
2022-11-03T03:41:34,821     self._link_candidate_cache[link] = LinkCandidate(
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
2022-11-03T03:41:34,821     super().__init__(
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
2022-11-03T03:41:34,821     self.dist = self._prepare()
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
2022-11-03T03:41:34,821     dist = self._prepare_distribution()
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
2022-11-03T03:41:34,821     return self._factory.preparer.prepare_linked_requirement(
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
2022-11-03T03:41:34,821     return self._prepare_linked_requirement(req, parallel_builds)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
2022-11-03T03:41:34,821     local_file = unpack_url(
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 208, in unpack_url
2022-11-03T03:41:34,821     unpack_vcs_link(link, location)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\operations\prepare.py", line 68, in unpack_vcs_link
2022-11-03T03:41:34,821     vcs_backend.unpack(location, url=hide_url(link.url))
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 626, in unpack
2022-11-03T03:41:34,821     self.obtain(location, url=url)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 534, in obtain
2022-11-03T03:41:34,821     self.fetch_new(dest, url, rev_options)
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\vcs\git.py", line 262, in fetch_new
2022-11-03T03:41:34,821     self.run_command(make_command('clone', '-q', url, dest))
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 669, in run_command
2022-11-03T03:41:34,821     return call_subprocess(cmd, show_stdout, cwd,
2022-11-03T03:41:34,821   File "C:\Users\lnico\anaconda3\lib\site-packages\pip\_internal\utils\subprocess.py", line 244, in call_subprocess
2022-11-03T03:41:34,821     raise InstallationSubprocessError(proc.returncode, command_desc)
2022-11-03T03:41:34,821 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 128: git clone -q https://github.com/ACCLAB/OSAR.git 'C:\Users\lnico\AppData\Local\Temp\pip-req-build-2b2cbp7u' Check the logs for full command output.
2022-11-03T03:41:34,860 Removed build tracker: 'C:\\Users\\lnico\\AppData\\Local\\Temp\\pip-req-tracker-xq96ynsj'
